version: "3"

services:
  app:
    container_name: mip-django
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    image: mip-django
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    networks:
      - default

  mongo:
    image: mongo
    container_name: mip-django.mongo
    restart: always
    volumes:
      - ./.docker-data/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      - default

  mongo-express:
    image: mongo-express
    container_name: mip-django.mongo.express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
    networks:
      - default

networks:
  default:
    external:
      name: local