# Generated by Django 2.2.6 on 2019-12-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='attachement',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
